# Services for W100 Smart Control integration

get_diagnostic_info:
  name: Get Diagnostic Information
  description: Generate diagnostic information for troubleshooting W100 Smart Control issues.
  fields:
    device_name:
      name: Device Name
      description: Name of the W100 device to get diagnostic info for (optional, uses primary device if not specified).
      example: "living_room_w100"
      selector:
        text:
    entry_id:
      name: Entry ID
      description: Configuration entry ID (optional, uses first available if not specified).
      example: "abc123def456"
      selector:
        text:

validate_setup:
  name: Validate Setup
  description: Validate the current W100 Smart Control setup and check for common issues.
  fields:
    entry_id:
      name: Entry ID
      description: Configuration entry ID (optional, uses first available if not specified).
      example: "abc123def456"
      selector:
        text: